general:
  cfApiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
  cfOrg: 'c7b2bc6dtrial'
  cfSpace: 'dev'
  cfCredentialsId: 'cfAuthentification'
  cfServiceInstance: 'rpa-developer'
  cfServiceKeyName: 'SAP_COM_0510'
stages:
  Clone Repositories:
    repositories: 'repositories.yml'
    strategy: 'Pull'
  ATC:
    atcConfig: 'atcConfig.yml'
